display:
  width: 1600
  height: 900
  caption: "Ciccio"

maze:
  min_rows: 3
  max_rows: 7
  min_cols: 4
  max_cols: 8

colors:
  white: [255, 255, 255]
  black: [0, 0, 0]
  green: [0, 255, 0]
  red: [255, 0, 0]
  blue: [0, 0, 255]

player:
  speed: 1
  size: 5